### ISSUE TITLE
Matching Network

### ISSUE THREAD

**Issue by meakash** [JackGruber/Arduino-Pro-Mini-LoRa-Sensor-Node#1]
Hi, Sorry to bother you, i was making a similar board and i was stuck at designing a matching network between the ant pin of RFM 95 and the SMA connector, wont that be a problem?

**Comment by JackGruber** [comment]
Hi, I'm not sure what do you mean.

The PCB trace between the ANT Pin and the SMA connector should be as short as possible.

**Comment by meakash** [comment]
Thank you for the prompt response.
What I am asking is that is there any need to a matching network between the ANT pin and SMA connector? 
I read it is always better to have a matching network as there may be losses if there is no matching netowrk.
Did you observe any bad results?

**Comment by JackGruber** [comment]
sorry, but I don't know what you mean by:
>any need to a matching network between the ANT pin and SMA connector?

**Comment by mkbehbeh** [comment]
I think that what meakash is referring to is the set of inductors/capacitors between the radio transmitter and antenna to match impedance and reduce reflections.  
If you look closely at the SX1272/76 board there is already a matching network there to match the LoRa chip to a 50ohm antenna.  As long as you keep your traces short (<< than 1/4 wavelenth) then you should only see the impedance of your monopole (short stub of wire) or dipole (rubber ducky style) which will be matched close enough to 50ohms to not cause a problem.  If you want to use a different antenna that is not matched to 50 ohms then you need to provide your own matching network.  You will also need a matching network if you need to have an extension to the antenna with a length not matched to a multiple of half wavelength.
